
-- =============================================
-- Deshabilitar RLS (para entorno de desarrollo)
-- =============================================

ALTER TABLE usuarios DISABLE ROW LEVEL SECURITY;
ALTER TABLE transacciones DISABLE ROW LEVEL SECURITY;
ALTER TABLE presupuestos DISABLE ROW LEVEL SECURITY;
ALTER TABLE metas_financieras DISABLE ROW LEVEL SECURITY;
ALTER TABLE planes DISABLE ROW LEVEL SECURITY;
ALTER TABLE currency_rates DISABLE ROW LEVEL SECURITY;
ALTER TABLE categories DISABLE ROW LEVEL SECURITY;
ALTER TABLE recurring_transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE notifications DISABLE ROW LEVEL SECURITY;
ALTER TABLE glossary DISABLE ROW LEVEL SECURITY;
ALTER TABLE help_center DISABLE ROW LEVEL SECURITY;
ALTER TABLE terms_privacy DISABLE ROW LEVEL SECURITY;
ALTER TABLE invoices DISABLE ROW LEVEL SECURITY;
ALTER TABLE mrr_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE ai_models DISABLE ROW LEVEL SECURITY;
ALTER TABLE ai_recommendations DISABLE ROW LEVEL SECURITY;
ALTER TABLE statistical_tests DISABLE ROW LEVEL SECURITY;
ALTER TABLE chatbot_conversations DISABLE ROW LEVEL SECURITY;
ALTER TABLE chatbot_limits DISABLE ROW LEVEL SECURITY;
ALTER TABLE invites DISABLE ROW LEVEL SECURITY;
ALTER TABLE reports DISABLE ROW LEVEL SECURITY;
ALTER TABLE feature_adoption DISABLE ROW LEVEL SECURITY;
