import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  es: {
    // ===== GENERAL =====
    login: 'Iniciar Sesión',
    register: 'Registrar',
    logout: 'Cerrar Sesión',
    dashboard: 'Panel',
    transactions: 'Transacciones',
    budgets: 'Presupuestos',
    goals: 'Metas',
    profile: 'Mi Perfil',
    settings: 'Configuración',
    plans: 'Planes',
    admin: 'Admin',
    users: 'Usuarios',
    statistics: 'Estadísticas',
    aiRecommendations: 'Recomendaciones IA',
    helpCenter: 'Centro de Ayuda',
    billing: 'Facturación',
    chat: 'Chat',
    theme: 'Tema',
    language: 'Idioma',
    light: 'Claro',
    dark: 'Oscuro',
    system: 'Sistema',
    save: 'Guardar',
    cancel: 'Cancelar',
    loading: 'Cargando...',
    error: 'Error',
    success: 'Éxito',
    credentialsIncorrect: 'Credenciales incorrectas',
    name: 'Nombre',
    email: 'Email',
    password: 'Contraseña',
    currentPassword: 'Contraseña Actual',
    newPassword: 'Nueva Contraseña',
    confirmPassword: 'Confirmar Contraseña',
    monthlyIncome: 'Ingreso Mensual',
    riskProfile: 'Perfil de Riesgo',
    advisorTone: 'Tono del Asesor',
    currency: 'Moneda',
    preferences: 'Preferencias',
    changePassword: 'Cambiar Contraseña',
    plan: 'Plan',
    role: 'Rol',
    basic: 'Básico',
    premium: 'Premium',
    enterprise: 'Enterprise',
    adminRole: 'Admin',
    welcome: 'Bienvenido',
    hello: 'Hola',
    goodbye: 'Adiós',
    createAccount: 'Crear Cuenta',
    startManaging: 'Comienza a gestionar tus finanzas',
    manageFinances: 'Gestiona tus finanzas de manera inteligente',
    choosePlan: 'Elegir Plan',
    creating: 'Creando...',
    passwordMismatch: 'Las contraseñas no coinciden',
    errorCreating: 'Error al crear la cuenta',
    yourEmail: 'tu@email.com',
    yourName: 'Tu nombre',
    haveAccount: '¿Ya tienes cuenta?',
    noAccount: '¿No tienes una cuenta?',
    signIn: 'Ingresa aquí',
    alreadyHave: 'Ya lo tienes',
    selectPlan: 'Selecciona tu Plan',
    perMonth: '/mes',
    planChangedTo: 'Plan cambiado a',
    redirecting: 'Redirigiendo...',
    mostPopular: 'Más Popular',
    retry: 'Reintentar',
    loadingDashboard: 'Cargando panel...',
    financialPanel: 'Panel financiero',
    dashboardDescription: 'Resumen operativo, recomendaciones inteligentes y alertas de ahorro.',
    generating: 'Generando...',
    generateReport: 'Generar Reporte PDF',
    aiPlan: 'Plan de IA',
    activeModels: 'Modelos activos',
    totalIncome: 'Ingresos Totales',
    totalExpenses: 'Gastos Totales',
    netSavings: 'Ahorro Neto',
    nextMonthPrediction: 'Predicción del próximo mes',
    projectedIncome: 'Ingreso proyectado',
    projectedExpenses: 'Gasto proyectado',
    projectedSavings: 'Ahorro proyectado',
    budgetAtRisk: 'Presupuesto en riesgo',
    expenseDistribution: 'Distribución de Gastos',
    budgetVsActual: 'Presupuesto vs Realidad',
    spendingTrends: 'Tendencias de Gastos',
    noExpenses: 'No hay gastos para mostrar',
    noBudgets: 'No hay presupuestos para mostrar',
    noTrendData: 'No hay datos suficientes para mostrar tendencias',
    visibleByPlan: 'visibles según tu plan',
    general: 'General',
    urgency: 'Urgencia',
    noRecommendations: 'No hay suficientes datos para generar recomendaciones.',
    recentTransactions: 'Transacciones Recientes',
    noTransactions: 'No hay transacciones registradas',
    searchByAccount: 'Buscar por cuenta...',
    noTransactionsFound: 'No se encontraron transacciones para esta cuenta',
    tryDifferentSearch: 'Prueba con otro término de búsqueda.',
    cuenta: 'Cuenta',

    // ===== GOALS =====
    loadingGoals: 'Cargando metas...',
    financialGoals: 'Metas Financieras',
    newGoal: 'Nueva Meta',
    current: 'Actual',
    target: 'Objetivo',
    deadline: 'Fecha Límite',
    add: 'Agregar',
    howMuchToAdd: '¿Cuánto quieres agregar?',
    confirmDeleteGoal: '¿Estás seguro de eliminar esta meta?',
    noGoals: 'No hay metas registradas',
    description: 'Descripción',
    targetAmount: 'Monto Objetivo',
    currentAmount: 'Monto Actual',
    create: 'Crear',
    searchGoal: 'Buscar meta por nombre...',
    noGoalsFound: 'No se encontraron metas',
    enterGoalName: 'Ingresa un nombre para la meta',
    enterValidTarget: 'Ingresa un monto objetivo válido',
    goalLimitReached: 'Has alcanzado el límite de metas en tu plan.',
    upgradeForMoreGoals: 'Actualiza a Premium para más metas o Enterprise para metas ilimitadas.',
    unlimited: 'Ilimitadas',
    progress: 'Progreso',
    limit: 'Límite',
    addToGoal: 'Agregar a meta',
    amountToAdd: 'Monto a agregar',
    remaining: 'Restante',
    adding: 'Agregando...',

    // ===== TRANSACTIONS =====
    loadingTransactions: 'Cargando transacciones...',
    newTransaction: 'Nueva Transacción',
    type: 'Tipo',
    expense: 'Gasto',
    income: 'Ingreso',
    amount: 'Monto',
    category: 'Categoría',
    date: 'Fecha',
    account: 'Cuenta',
    confirmDeleteTransaction: '¿Estás seguro de eliminar esta transacción?',
    noTransactionsYet: 'No hay transacciones registradas',
    myTransactions: 'Mis Transacciones',
    editTransaction: 'Editar Transacción',
    recurring: 'Recurrente',
    actions: 'Acciones',
    edit: 'Editar',
    delete: 'Eliminar',
    confirmDelete: '¿Estás seguro de que quieres eliminar esta transacción?',

    // ===== BUDGETS =====
    loadingBudgets: 'Cargando presupuestos...',
    newBudget: 'Nuevo Presupuesto',
    confirmDeleteBudget: '¿Estás seguro de eliminar este presupuesto?',
    period: 'Periodo',
    monthlyLimit: 'Límite Mensual',
    myBudgets: 'Mis Presupuestos',
    budgetLimit: 'Límite de Presupuesto',
    spent: 'Gastado',
    noBudgetsYet: 'No tienes presupuestos aún',

    // ===== CHATBOT =====
    financialAssistant: 'Asistente Financiero',
    typeMessage: 'Escribe tu mensaje...',
    initialBotMessage: '¡Hola! Soy tu asistente financiero personal. ¿En qué puedo ayudarte hoy?',
    botResponses: [
      'Revisa tus gastos recientes; has gastado bastante en entretenimiento.',
      'Tu ahorro actual es bueno, sigue así.',
      '¿Has considerado crear un presupuesto para tus comidas fuera de casa?',
      'Tienes una meta de ahorro activa, ¡no olvides contribuir!',
      'Recomiendo revisar tus suscripciones mensuales para ver si hay alguna que no uses.',
      'Tu flujo de caja es positivo este mes. ¡Bien hecho!',
    ],
    chatWelcome: '¡Hola! 👋 Soy tu asistente financiero de FinanciaUNT. ¿En qué puedo ayudarte hoy?',
    chatPlaceholder: 'Escribe tu mensaje...',
    chatUpgradeRequired: 'El chat con IA está disponible solo para usuarios con plan Premium o Enterprise. Actualiza tu plan para activar esta función.',
    chatProcessing: '¡Gracias por tu mensaje! Estoy procesando tu solicitud.',
    chatError: 'No pude responder en este momento. Inténtalo otra vez.',
    thinking: 'Pensando...',

    // ===== VOICE INPUT =====
    voiceInput: 'Entrada por voz',
    voiceInputPremium: 'La entrada por voz está disponible en planes Premium y Enterprise. Actualiza tu plan para usar esta función.',

    // ===== AI RECOMMENDATIONS =====
    aiPersonalized: 'IA personalizada',
    aiTitle: 'Recomendaciones de IA',
    aiSubtitle: 'Análisis inteligente con 3 modelos predictivos',
    loadingAI: 'Cargando...',
    dominantModel: 'Modelo dominante',
    estimatedImpact: 'Impacto estimado',
    visibleRecommendations: 'Recomendaciones visibles',
    modelsSection: 'Modelos de Recomendación',
    models: 'modelos',
    modelsDescription: 'Cada modelo analiza tus finanzas desde una perspectiva diferente.',
    comparatorWeight: 'Peso',
    metricPrecision: 'Precisión@5',
    metricNdcg: 'NDCG@10',
    metricUplift: 'Uplift de ahorro',
    metricsAvailablePremium: 'Métricas disponibles en Premium y Enterprise',
    noStats: 'Sin datos',
    comparatorTitle: 'Comparador – Recomendaciones combinadas',
    comparatorDescription: 'Las mejores recomendaciones de los 3 modelos, ponderadas y ordenadas por puntuación.',
    score: 'Puntuación',
    impact: 'Impacto',
    accept: 'Aceptar',
    accepted: 'Aceptada',
    noAIRecommendations: 'No hay recomendaciones disponibles.',
    statsTitle: 'Estadísticas comparativas',
    hide: 'Ocultar',
    show: 'Mostrar',
    statsDescription: 'Pruebas estadísticas para evaluar el rendimiento relativo de cada modelo.',
    precisionChart: 'Precisión@5 por modelo',
    precisionChartDesc: 'Porcentaje de aciertos en las primeras 5 recomendaciones. Valores más altos indican mejor capacidad de predicción.',
    precisionInterpretation: 'El modelo con mayor precisión es {best}, lo que significa que es el que mejor acierta al predecir recomendaciones útiles para ti.',
    ndcgChart: 'NDCG@10 por modelo',
    ndcgChartDesc: 'Normalized Discounted Cumulative Gain: mide la calidad del ranking en las 10 primeras posiciones. 1 = ranking perfecto.',
    ndcgInterpretation: 'El modelo con mejor ranking es {best}, lo que indica que coloca las recomendaciones más relevantes en las primeras posiciones.',
    upliftChart: 'Uplift de ahorro por modelo',
    upliftChartDesc: 'Incremento promedio en ahorro generado por las recomendaciones del modelo (en moneda local).',
    upliftInterpretation: 'El modelo que genera mayor ahorro es {best}, con un incremento promedio de {amount}.',
    performanceMetrics: 'Métricas de rendimiento',
    metricsTableDesc: 'Comparativa numérica de los tres modelos. El valor más alto en cada columna está resaltado.',
    metricsInterpretation: 'En general, {precision} destaca en precisión, {ndcg} en ranking, y {uplift} en ahorro generado.',
    model: 'Modelo',
    noStatsData: 'No hay datos suficientes para mostrar gráficos.',
    statisticalTests: 'Pruebas estadísticas',
    testsDescription: 'Estas pruebas nos ayudan a determinar si las diferencias entre los modelos son estadísticamente significativas o podrían deberse al azar.',
    testFriedman: 'Friedman',
    friedmanExplanation: 'Compara el rendimiento global de todos los modelos simultáneamente. Un resultado "No significativo" indica que no hay diferencias claras entre ellos en conjunto.',
    friedmanSignificant: '✅ La prueba de Friedman muestra diferencias significativas entre los modelos (p = {p}).',
    friedmanNotSignificant: '❌ La prueba de Friedman NO muestra diferencias significativas (p = {p}).',
    significant: 'Significativo',
    notSignificant: 'No significativo',
    pairs: 'Pares',
    significantPairs: 'Significativos',
    wilcoxonSummary: 'De los {total} pares comparados, {sig} muestran diferencias significativas.',
    testWilcoxon: 'Comparaciones por pares (Wilcoxon)',
    wilcoxonDescription: 'Esta prueba identifica qué pares de modelos son estadísticamente diferentes entre sí.',
    pairInterpretation: 'El par {pair} muestra diferencias significativas, lo que indica que sus rendimientos son distintos.',
    wilcoxonConclusion: 'En conclusión, {sigCount} de {total} pares mostraron diferencias significativas, lo que sugiere que algunos modelos son claramente superiores a otros en términos de rendimiento.',
    wilcoxonSignificantPairs: '✅ La prueba de Wilcoxon confirma diferencias significativas en {sig} pares.',
    wilcoxonNoSignificant: '❌ La prueba de Wilcoxon NO encuentra diferencias significativas.',
    finalConclusion: 'Comparación final de modelos',
    conclusionWinner: '✅ El modelo ganador es {model}',
    conclusionRecommendation: 'Te recomendamos utilizar este modelo para obtener las mejores recomendaciones.',
    strengthsByModel: 'Fortalezas por modelo:',
    noStrengths: 'Sin fortalezas destacadas',
    strengthPrecision: 'Mejor precisión',
    strengthNdcg: 'Mejor ranking (NDCG)',
    strengthUplift: 'Mayor impacto en ahorro',
    upgradeTitle: 'Desbloquea más funciones',
    statsAvailablePremium: 'Las pruebas estadísticas están disponibles en Premium y Enterprise.',
    testResults: 'Resultados de pruebas',
    modelRulesDesc: 'Aplica reglas predefinidas basadas en tus presupuestos y tasa de ahorro.',
    modelCollaborativeDesc: 'Compara tu perfil de gasto con usuarios similares para encontrar oportunidades de mejora.',
    modelOptimizerDesc: 'Analiza tendencias y volatilidad para optimizar tu ahorro a futuro.',

    // ADMIN:
    "aiModelsInfoTitle": "Modelos de IA y Pruebas Estadísticas",
    "aiModelsIntroTitle": "¿Qué son los modelos de IA en FinanciaUNT?",
    "aiModelsIntroText": "FinanciaUNT utiliza tres modelos de inteligencia artificial para generar recomendaciones financieras personalizadas. Cada modelo analiza tus datos desde una perspectiva diferente, permitiendo obtener sugerencias más completas y precisas.",
    "aiModelsIntroText2": "Además, se aplican pruebas estadísticas para evaluar la calidad y confiabilidad de cada modelo, asegurando que las recomendaciones sean realmente útiles para los usuarios.",

    "aiModelsTitle": "Modelos de Recomendación",
    "modelRulesLabel": "Reglas",
    "modelRulesName": "Modelo de Reglas",
    "modelRulesDescription": "Este modelo aplica reglas predefinidas basadas en los presupuestos del usuario y su tasa de ahorro. Identifica gastos excesivos y sugiere ajustes automáticos.",
    "modelRulesWhen": "Ideal para usuarios que necesitan control básico de sus gastos y presupuestos.",

    "modelCollabLabel": "Colaborativo",
    "modelCollabName": "Modelo Colaborativo",
    "modelCollabDescription": "Compara el perfil de gasto del usuario con usuarios similares para encontrar oportunidades de mejora. Es útil para descubrir patrones de ahorro que otros ya aplican.",
    "modelCollabWhen": "Recomendado para usuarios que quieren aprender de las mejores prácticas de otros.",

    "modelSavingsLabel": "Optimizador",
    "modelSavingsName": "Modelo Optimizador de Ahorro",
    "modelSavingsDescription": "Analiza tendencias y volatilidad en los gastos para optimizar el ahorro futuro. Es el modelo más avanzado y sugiere estrategias a largo plazo.",
    "modelSavingsWhen": "Perfecto para usuarios con objetivos de ahorro a largo plazo o inversiones.",

    "whenToUse": "Cuándo usarlo",

    "statisticalTestsTitle": "Pruebas Estadísticas Utilizadas",
    "statisticalTestsIntro": "Para garantizar la calidad de las recomendaciones, aplicamos dos pruebas estadísticas que evalúan el rendimiento de los modelos de IA:",

    "testFriedmanName": "1. Prueba de Friedman",
    "friedmanDescription": "Esta prueba no paramétrica compara el rendimiento global de los tres modelos simultáneamente. Responde a la pregunta: '¿Existen diferencias estadísticamente significativas entre el rendimiento de los modelos?'",
    "friedmanResult": "Resultado",
    "friedmanResultText": "Si el p-valor es menor a 0.05 (5% de significancia), concluimos que al menos un modelo es diferente a los demás. Si es mayor, no hay evidencia suficiente para afirmar diferencias.",
    "whenToUseFriedman": "Cuándo se usa",
    "whenToUseFriedmanText": "Siempre que se quiera evaluar si los modelos tienen un desempeño similar o hay uno que destaca sobre los demás.",

    "testWilcoxonName": "2. Prueba de Wilcoxon (post-hoc)",
    "wilcoxonDescription": "Mientras la prueba de Friedman evalúa si hay diferencias globales, la prueba de Wilcoxon se aplica para identificar qué pares de modelos son diferentes entre sí. Es un análisis post-hoc o de seguimiento.",
    "wilcoxonResult": "Resultado",
    "wilcoxonResultText": "Se compara cada par de modelos (Reglas vs Colaborativo, Reglas vs Optimizador, Colaborativo vs Optimizador) para determinar si sus diferencias son significativas.",
    "whenToUseWilcoxon": "Cuándo se usa",
    "whenToUseWilcoxonText": "Cuando la prueba de Friedman indica que existen diferencias, este test ayuda a identificar exactamente qué modelo es superior.",

    "effectSizeTitle": "3. Tamaño del Efecto (Cohen's d)",
    "effectSizeDescription": "Además del p-valor, calculamos el 'tamaño del efecto' (Cohen's d) para entender la magnitud de las diferencias entre modelos. Esto complementa la significancia estadística con la relevancia práctica.",
    "effectSizeInterpretation": "Interpretación",
    "effectSizeInterpretationText": "Valores de d ≈ 0.2 indican un efecto pequeño, d ≈ 0.5 es moderado y d ≈ 0.8 es grande. Esto ayuda a decidir si una diferencia, aunque significativa, es realmente importante para el usuario.",

    "performanceMetricsTitle": "Métricas de Rendimiento",
    "performanceMetricsIntro": "Para evaluar la calidad de las recomendaciones generadas por cada modelo, utilizamos tres métricas clave:",
    "metricPrecisionName": "Precisión@5",
    "metricPrecisionDescription": "Mide el porcentaje de recomendaciones útiles entre las primeras 5 sugeridas por el modelo. Una mayor precisión indica que el modelo acierta más en sus primeras recomendaciones.",
    "metricNdcgName": "NDCG@10",
    "metricNdcgDescription": "Evalúa la calidad del ranking de las 10 primeras recomendaciones, considerando el orden de relevancia. Un valor cercano a 1 significa un ranking perfecto.",
    "metricUpliftName": "Savings Uplift",
    "metricUpliftDescription": "Incremento promedio en el ahorro que generan las recomendaciones del modelo. Se expresa en moneda local (PEN, USD, etc.) y refleja el impacto financiero real.",

    "comparatorTitle": "Comparador de Modelos",
    "comparatorDescription": "El sistema también incluye un 'Comparador' que combina las recomendaciones de los 3 modelos, ponderadas según su peso y relevancia. Esto permite ofrecer al usuario las recomendaciones más equilibradas y efectivas.",
    "howItWorks": "Cómo funciona",
    "howItWorksText": "Cada recomendación recibe una puntuación basada en su urgencia y el peso del modelo que la generó. Luego se ordenan por esa puntuación y se presentan al usuario en orden de prioridad.",
    "comparatorNote": "Nota: El Comparador está disponible para todos los planes, pero el número de recomendaciones visibles depende del plan del usuario (3 para Básico, 10 para Premium y Enterprise).",

    // ===== CURRENCY RATES =====
    exchangeRates: 'Tipos de Cambio',
    currencies: 'divisas',
    lastUpdate: 'Última actualización',
    autoUpdate: 'Actualización automática',
    loadingRates: 'Cargando tipos de cambio...',
    errorLoadingRates: 'Error al cargar tipos de cambio',
    baseCurrency: 'Moneda base',
    allAmountsInThisCurrency: 'todos los montos se muestran en esta moneda',
    noCurrenciesAvailable: 'No hay divisas disponibles para mostrar',
    noData: 'Sin datos',
    vsYesterday: 'vs ayer',
    upgradeForMoreCurrencies: 'Actualiza a Premium o Enterprise para ver más divisas.',
    registrationDate: 'Fecha de Registro',
    userManagement: 'Gestión de usuarios',

    // ===== VERIFICATION & PAYMENT =====
    verifyEmail: 'Verificar correo electrónico',
    enterCodeSentTo: 'Código enviado a ',
    emailVerificationRequired: 'Verificación de correo electrónico requerida',
    verifyYourEmail: 'Verifica tu correo electrónico',
    weSentCode: 'Hemos enviado un código de verificación a tu correo electrónico.',
    enterCode: 'Ingresa el código',
    verificationCode: 'Código de verificación',
    verify: 'Verificar',
    resendCode: 'Reenviar código',
    invalidCode: 'Código inválido',
    codeExpired: 'Código expirado',
    cardholderName: 'Titular de la tarjeta',
    cardNumber: 'Número de tarjeta',
    expiry: 'Vencimiento',
    cvv: 'CVV',
    payment: 'Pago',
    enterPaymentDetails: 'Ingresa tus datos de pago a continuación.',
    confirmPayment: 'Confirmar pago',
    processing: 'Procesando...',

    // ===== ADMIN =====
    loadingStats: 'Cargando estadísticas...',
    generalStats: 'Estadísticas Generales',
    totalUsers: 'Total Usuarios',
    totalTransactions: 'Total Transacciones',
    expensesByUser: 'Gastos por Usuario',
    incomeVsExpenses: 'Resumen Ingresos vs Gastos',
    noExpenseData: 'No hay datos de gastos',
    user: 'Usuario',
    aiStats: 'Estadísticas IA',
    adminUsers: 'Usuarios',
    allUsers: 'Todos los Usuarios',
    emailVerified: 'Correo Verificado',
    createdAt: 'Creado',

    // ===== FEATURES =====
    features: {
      theme: 'Tema claro/oscuro',
      language: 'Cambio de idioma (Español/Inglés)',
      basicPanel: 'Panel financiero completo',
      basicCurrency: 'Tipos de cambio PEN/USD',
      basicAI: 'Modelos de recomendación IA',
      basicComparator: 'Comparador de recomendaciones (hasta 3)',
      basicTransactions: 'Registro de transacciones, presupuestos y metas',
      basicCategories: 'Categorías básicas (9)',
      basicChat: 'Chatbot (10 intentos diarios)',
      basicProfile: 'Perfil de usuario',
      premiumCurrency: 'Tipos de cambio +EUR, MXN',
      premiumComparator: 'Comparador de recomendaciones (hasta 10)',
      premiumStats: 'Estadísticas comparativas + pruebas estadísticas',
      premiumCategories: '5 categorías adicionales (total 14)',
      premiumChat: 'Chatbot ilimitado + entrada por voz',
      enterpriseCurrency: 'Tipos de cambio +30 monedas globales',
      enterpriseCategories: '10 categorías adicionales (total 24)',
    },
    basicSummary: 'Para empezar a organizar tus finanzas con herramientas básicas.',
    premiumSummary: 'Ideal para quienes buscan estadísticas avanzadas y más flexibilidad.',
    enterpriseSummary: 'Para empresas o usuarios avanzados con necesidades globales.',

    // ===== DOWNGRADE =====
    downgradeWarning: '¡Atención! Estás bajando de plan',
    downgradeMessage: 'Al bajar de plan, perderás las siguientes funcionalidades:',
    downgradeFeature1: 'Acceso a métricas avanzadas de IA',
    downgradeFeature2: 'Necesitarás volver a ingresar tus datos bancarios',
    downgradeFeature3: 'Las recomendaciones se limitarán al plan seleccionado',
    confirmDowngrade: 'Sí, estoy seguro',
  },

  // =========================================================================
  // INGLÉS
  // =========================================================================
  en: {
    // ===== GENERAL =====
    login: 'Sign In',
    register: 'Register',
    logout: 'Sign Out',
    dashboard: 'Dashboard',
    transactions: 'Transactions',
    budgets: 'Budgets',
    goals: 'Goals',
    profile: 'My Profile',
    settings: 'Settings',
    plans: 'Plans',
    admin: 'Admin',
    users: 'Users',
    statistics: 'Statistics',
    aiRecommendations: 'AI Recommendations',
    helpCenter: 'Help Center',
    billing: 'Billing',
    chat: 'Chat',
    theme: 'Theme',
    language: 'Language',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    save: 'Save',
    cancel: 'Cancel',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    credentialsIncorrect: 'Incorrect credentials',
    name: 'Name',
    email: 'Email',
    password: 'Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    monthlyIncome: 'Monthly Income',
    riskProfile: 'Risk Profile',
    advisorTone: 'Advisor Tone',
    currency: 'Currency',
    preferences: 'Preferences',
    changePassword: 'Change Password',
    plan: 'Plan',
    role: 'Role',
    basic: 'Basic',
    premium: 'Premium',
    enterprise: 'Enterprise',
    adminRole: 'Admin',
    welcome: 'Welcome',
    hello: 'Hello',
    goodbye: 'Goodbye',
    createAccount: 'Create Account',
    startManaging: 'Start managing your finances',
    manageFinances: 'Manage your finances smartly',
    choosePlan: 'Choose Plan',
    creating: 'Creating...',
    passwordMismatch: 'Passwords do not match',
    errorCreating: 'Error creating account',
    yourEmail: 'your@email.com',
    yourName: 'Your name',
    haveAccount: 'Already have an account?',
    noAccount: "Don't have an account?",
    signIn: 'Sign in here',
    alreadyHave: 'You already have it',
    selectPlan: 'Choose your Plan',
    perMonth: '/month',
    planChangedTo: 'Plan changed to',
    redirecting: 'Redirecting...',
    mostPopular: 'Most Popular',
    retry: 'Retry',
    loadingDashboard: 'Loading dashboard...',
    financialPanel: 'Financial Panel',
    dashboardDescription: 'Operational summary, smart recommendations and savings alerts.',
    generating: 'Generating...',
    generateReport: 'Generate PDF Report',
    aiPlan: 'AI Plan',
    activeModels: 'Active models',
    totalIncome: 'Total Income',
    totalExpenses: 'Total Expenses',
    netSavings: 'Net Savings',
    nextMonthPrediction: 'Next month prediction',
    projectedIncome: 'Projected income',
    projectedExpenses: 'Projected expenses',
    projectedSavings: 'Projected savings',
    budgetAtRisk: 'Budget at risk',
    expenseDistribution: 'Expense Distribution',
    budgetVsActual: 'Budget vs Actual',
    spendingTrends: 'Spending Trends',
    noExpenses: 'No expenses to show',
    noBudgets: 'No budgets to show',
    noTrendData: 'Not enough data to show trends',
    visibleByPlan: 'visible by your plan',
    general: 'General',
    urgency: 'Urgency',
    noRecommendations: 'Not enough data to generate recommendations.',
    recentTransactions: 'Recent Transactions',
    noTransactions: 'No transactions registered',
    searchByAccount: 'Search by account...',
    noTransactionsFound: 'No transactions found for this account',
    tryDifferentSearch: 'Try a different search term.',
    cuenta: 'Account',

    // ===== GOALS =====
    loadingGoals: 'Loading goals...',
    financialGoals: 'Financial Goals',
    newGoal: 'New Goal',
    current: 'Current',
    target: 'Target',
    deadline: 'Deadline',
    add: 'Add',
    howMuchToAdd: 'How much do you want to add?',
    confirmDeleteGoal: 'Are you sure you want to delete this goal?',
    noGoals: 'No goals registered',
    description: 'Description',
    targetAmount: 'Target Amount',
    currentAmount: 'Current Amount',
    create: 'Create',
    searchGoal: 'Search goal by name...',
    noGoalsFound: 'No goals found',
    enterGoalName: 'Enter a name for the goal',
    enterValidTarget: 'Enter a valid target amount',
    goalLimitReached: 'You have reached the goals limit in your plan.',
    upgradeForMoreGoals: 'Upgrade to Premium for more goals or Enterprise for unlimited goals.',
    unlimited: 'Unlimited',
    progress: 'Progress',
    limit: 'Limit',
    addToGoal: 'Add to goal',
    amountToAdd: 'Amount to add',
    remaining: 'Remaining',
    adding: 'Adding...',

    // ===== TRANSACTIONS =====
    loadingTransactions: 'Loading transactions...',
    newTransaction: 'New Transaction',
    type: 'Type',
    expense: 'Expense',
    income: 'Income',
    amount: 'Amount',
    category: 'Category',
    date: 'Date',
    account: 'Account',
    confirmDeleteTransaction: 'Are you sure you want to delete this transaction?',
    noTransactionsYet: 'No transactions registered',
    myTransactions: 'My Transactions',
    editTransaction: 'Edit Transaction',
    recurring: 'Recurring',
    actions: 'Actions',
    edit: 'Edit',
    delete: 'Delete',
    confirmDelete: 'Are you sure you want to delete this transaction?',

    // ===== BUDGETS =====
    loadingBudgets: 'Loading budgets...',
    newBudget: 'New Budget',
    confirmDeleteBudget: 'Are you sure you want to delete this budget?',
    period: 'Period',
    monthlyLimit: 'Monthly Limit',
    myBudgets: 'My Budgets',
    budgetLimit: 'Budget Limit',
    spent: 'Spent',
    noBudgetsYet: "You don't have any budgets yet",

    // ===== CHATBOT =====
    financialAssistant: 'Financial Assistant',
    typeMessage: 'Type your message...',
    initialBotMessage: 'Hello! I am your personal financial assistant. How can I help you today?',
    botResponses: [
      'Check your recent expenses; you have spent quite a bit on entertainment.',
      'Your current savings are good, keep it up.',
      'Have you considered creating a budget for eating out?',
      'You have an active savings goal, don\'t forget to contribute!',
      'I recommend reviewing your monthly subscriptions to see if there is any you don\'t use.',
      'Your cash flow is positive this month. Well done!',
    ],
    chatWelcome: 'Hello! 👋 I am your FinanciaUNT financial assistant. How can I help you today?',
    chatPlaceholder: 'Type your message...',
    chatUpgradeRequired: 'AI chat is only available for Premium or Enterprise plan users. Upgrade your plan to activate this feature.',
    chatProcessing: 'Thank you for your message! I am processing your request.',
    chatError: 'I could not respond at this time. Please try again.',
    thinking: 'Thinking...',
    registrationDate: 'Registration Date',
    userManagement: 'User Management',

    // ===== VOICE INPUT =====
    voiceInput: 'Voice input',
    voiceInputPremium: 'Voice input is available on Premium and Enterprise plans. Upgrade your plan to use this feature.',

    // ===== AI RECOMMENDATIONS =====
    aiPersonalized: 'Personalized AI',
    aiTitle: 'AI Recommendations',
    aiSubtitle: 'Smart analysis with 3 predictive models',
    loadingAI: 'Loading...',
    dominantModel: 'Dominant model',
    estimatedImpact: 'Estimated impact',
    visibleRecommendations: 'Visible recommendations',
    modelsSection: 'Recommendation Models',
    models: 'models',
    modelsDescription: 'Each model analyzes your finances from a different perspective.',
    comparatorWeight: 'Weight',
    metricPrecision: 'Precision@5',
    metricNdcg: 'NDCG@10',
    metricUplift: 'Savings Uplift',
    metricsAvailablePremium: 'Metrics available in Premium and Enterprise',
    noStats: 'No data',
    comparatorTitle: 'Comparator – Combined recommendations',
    comparatorDescription: 'The best recommendations from the 3 models, weighted and sorted by score.',
    score: 'Score',
    impact: 'Impact',
    accept: 'Accept',
    accepted: 'Accepted',
    noAIRecommendations: 'No recommendations available.',
    statsTitle: 'Comparative statistics',
    hide: 'Hide',
    show: 'Show',
    statsDescription: 'Statistical tests to evaluate the relative performance of each model.',
    precisionChart: 'Precision@5 by model',
    precisionChartDesc: 'Percentage of hits in the first 5 recommendations. Higher values indicate better predictive ability.',
    precisionInterpretation: 'The model with the highest precision is {best}, meaning it best predicts useful recommendations for you.',
    ndcgChart: 'NDCG@10 by model',
    ndcgChartDesc: 'Normalized Discounted Cumulative Gain: measures ranking quality in the top 10 positions. 1 = perfect ranking.',
    ndcgInterpretation: 'The model with the best ranking is {best}, which places the most relevant recommendations at the top.',
    upliftChart: 'Savings Uplift by model',
    upliftChartDesc: 'Average increase in savings generated by the model\'s recommendations (in local currency).',
    upliftInterpretation: 'The model that generates the most savings is {best}, with an average increase of {amount}.',
    performanceMetrics: 'Performance metrics',
    metricsTableDesc: 'Numerical comparison of the three models. The highest value in each column is highlighted.',
    metricsInterpretation: 'Overall, {precision} stands out in precision, {ndcg} in ranking, and {uplift} in savings generation.',
    model: 'Model',
    noStatsData: 'Insufficient data to display charts.',
    statisticalTests: 'Statistical tests',
    testsDescription: 'These tests help determine whether differences between models are statistically significant or could be due to chance.',
    testFriedman: 'Friedman',
    friedmanExplanation: 'Compares the overall performance of all models simultaneously. A "Not significant" result indicates no clear differences among them overall.',
    friedmanSignificant: '✅ Friedman test shows significant differences between models (p = {p}).',
    friedmanNotSignificant: '❌ Friedman test shows NO significant differences (p = {p}).',
    significant: 'Significant',
    notSignificant: 'Not significant',
    pairs: 'Pairs',
    significantPairs: 'Significant',
    wilcoxonSummary: 'Out of {total} pairs compared, {sig} show significant differences.',
    testWilcoxon: 'Pairwise comparisons (Wilcoxon)',
    wilcoxonDescription: 'This test identifies which pairs of models are statistically different from each other.',
    pairInterpretation: 'The pair {pair} shows significant differences, indicating their performance is distinct.',
    wilcoxonConclusion: 'In conclusion, {sigCount} out of {total} pairs showed significant differences, suggesting some models are clearly superior to others in terms of performance.',
    wilcoxonSignificantPairs: '✅ Wilcoxon test confirms significant differences in {sig} pairs.',
    wilcoxonNoSignificant: '❌ Wilcoxon test finds NO significant differences.',
    finalConclusion: 'Final model comparison',
    conclusionWinner: '✅ The winning model is {model}',
    conclusionRecommendation: 'We recommend using this model to get the best recommendations.',
    strengthsByModel: 'Strengths by model:',
    noStrengths: 'No notable strengths',
    strengthPrecision: 'Best precision',
    strengthNdcg: 'Best ranking (NDCG)',
    strengthUplift: 'Highest savings impact',
    upgradeTitle: 'Unlock more features',
    statsAvailablePremium: 'Statistical tests are available in Premium and Enterprise.',
    testResults: 'Test results',
    modelRulesDesc: 'Applies predefined rules based on your budgets and savings rate.',
    modelCollaborativeDesc: 'Compares your spending profile with similar users to find improvement opportunities.',
    modelOptimizerDesc: 'Analyzes trends and volatility to optimize your future savings.',

    // ADMIN:
    "aiModelsInfoTitle": "AI Models and Statistical Tests",
    "aiModelsIntroTitle": "What are AI models in FinanciaUNT?",
    "aiModelsIntroText": "FinanciaUNT uses three artificial intelligence models to generate personalized financial recommendations. Each model analyzes your data from a different perspective, providing more comprehensive and accurate suggestions.",
    "aiModelsIntroText2": "Additionally, statistical tests are applied to evaluate the quality and reliability of each model, ensuring that the recommendations are truly useful for users.",

    "aiModelsTitle": "Recommendation Models",
    "modelRulesLabel": "Rules",
    "modelRulesName": "Rules Model",
    "modelRulesDescription": "This model applies predefined rules based on the user's budgets and savings rate. It identifies excessive spending and suggests automatic adjustments.",
    "modelRulesWhen": "Ideal for users who need basic control over their spending and budgets.",

    "modelCollabLabel": "Collaborative",
    "modelCollabName": "Collaborative Model",
    "modelCollabDescription": "Compares the user's spending profile with similar users to find improvement opportunities. It's useful for discovering saving patterns that others are already applying.",
    "modelCollabWhen": "Recommended for users who want to learn from other users' best practices.",

    "modelSavingsLabel": "Optimizer",
    "modelSavingsName": "Savings Optimizer Model",
    "modelSavingsDescription": "Analyzes trends and volatility in spending to optimize future savings. It is the most advanced model and suggests long-term strategies.",
    "modelSavingsWhen": "Perfect for users with long-term savings goals or investments.",

    "whenToUse": "When to use",

    "statisticalTestsTitle": "Statistical Tests Used",
    "statisticalTestsIntro": "To ensure the quality of recommendations, we apply two statistical tests that evaluate the performance of the AI models:",

    "testFriedmanName": "1. Friedman Test",
    "friedmanDescription": "This non-parametric test compares the overall performance of the three models simultaneously. It answers: 'Are there statistically significant differences between the models' performance?'",
    "friedmanResult": "Result",
    "friedmanResultText": "If the p-value is less than 0.05 (5% significance), we conclude that at least one model differs from the others. If it is higher, there is not enough evidence to claim differences.",
    "whenToUseFriedman": "When to use",
    "whenToUseFriedmanText": "Whenever you want to evaluate whether the models have similar performance or if one stands out from the others.",

    "testWilcoxonName": "2. Wilcoxon Test (post-hoc)",
    "wilcoxonDescription": "While the Friedman test evaluates whether there are global differences, the Wilcoxon test is applied to identify which pairs of models are different from each other. It is a post-hoc or follow-up analysis.",
    "wilcoxonResult": "Result",
    "wilcoxonResultText": "Each pair of models is compared (Rules vs Collaborative, Rules vs Optimizer, Collaborative vs Optimizer) to determine if their differences are significant.",
    "whenToUseWilcoxon": "When to use",
    "whenToUseWilcoxonText": "When the Friedman test indicates that differences exist, this test helps identify exactly which model is superior.",

    "effectSizeTitle": "3. Effect Size (Cohen's d)",
    "effectSizeDescription": "In addition to the p-value, we calculate the 'effect size' (Cohen's d) to understand the magnitude of differences between models. This complements statistical significance with practical relevance.",
    "effectSizeInterpretation": "Interpretation",
    "effectSizeInterpretationText": "Values of d ≈ 0.2 indicate a small effect, d ≈ 0.5 is moderate, and d ≈ 0.8 is large. This helps decide whether a difference, although significant, is truly important for the user.",

    "performanceMetricsTitle": "Performance Metrics",
    "performanceMetricsIntro": "To evaluate the quality of recommendations generated by each model, we use three key metrics:",
    "metricPrecisionName": "Precision@5",
    "metricPrecisionDescription": "Measures the percentage of useful recommendations among the first 5 suggested by the model. Higher precision indicates the model is more accurate in its first recommendations.",
    "metricNdcgName": "NDCG@10",
    "metricNdcgDescription": "Evaluates the ranking quality of the first 10 recommendations, considering the order of relevance. A value close to 1 means a perfect ranking.",
    "metricUpliftName": "Savings Uplift",
    "metricUpliftDescription": "Average increase in savings generated by the model's recommendations. It is expressed in local currency (PEN, USD, etc.) and reflects the real financial impact.",

    "comparatorTitle": "Model Comparator",
    "comparatorDescription": "The system also includes a 'Comparator' that combines recommendations from all 3 models, weighted according to their relevance and importance. This allows offering the user the most balanced and effective recommendations.",
    "howItWorks": "How it works",
    "howItWorksText": "Each recommendation receives a score based on its urgency and the weight of the model that generated it. They are then sorted by that score and presented to the user in order of priority.",
    "comparatorNote": "Note: The Comparator is available for all plans, but the number of visible recommendations depends on the user's plan (3 for Basic, 10 for Premium and Enterprise).",

    // ===== CURRENCY RATES =====
    exchangeRates: 'Exchange Rates',
    currencies: 'currencies',
    lastUpdate: 'Last updated',
    autoUpdate: 'Auto update',
    loadingRates: 'Loading exchange rates...',
    errorLoadingRates: 'Error loading exchange rates',
    baseCurrency: 'Base currency',
    allAmountsInThisCurrency: 'all amounts are shown in this currency',
    noCurrenciesAvailable: 'No currencies available to show',
    noData: 'No data',
    vsYesterday: 'vs yesterday',
    upgradeForMoreCurrencies: 'Upgrade to Premium or Enterprise to see more currencies.',

    // ===== VERIFICATION & PAYMENT =====
    verifyEmail: 'Verify email',
    enterCodeSentTo: 'Code sent to ',
    emailVerificationRequired: 'Email verification required',
    verifyYourEmail: 'Verify your email',
    weSentCode: 'We have sent a verification code to your email.',
    enterCode: 'Enter the code',
    verificationCode: 'Verification code',
    verify: 'Verify',
    resendCode: 'Resend code',
    invalidCode: 'Invalid code',
    codeExpired: 'Code expired',
    cardholderName: 'Cardholder name',
    cardNumber: 'Card number',
    expiry: 'Expiry',
    cvv: 'CVV',
    payment: 'Payment',
    enterPaymentDetails: 'Enter your payment details below.',
    confirmPayment: 'Confirm payment',
    processing: 'Processing...',

    // ===== ADMIN =====
    loadingStats: 'Loading statistics...',
    generalStats: 'General Statistics',
    totalUsers: 'Total Users',
    totalTransactions: 'Total Transactions',
    expensesByUser: 'Expenses by User',
    incomeVsExpenses: 'Income vs Expenses Summary',
    noExpenseData: 'No expense data',
    user: 'User',
    aiStats: 'AI Statistics',
    adminUsers: 'Users',
    allUsers: 'All Users',
    emailVerified: 'Email Verified',
    createdAt: 'Created At',

    // ===== FEATURES =====
    features: {
      theme: 'Light/Dark theme',
      language: 'Language switch (Spanish/English)',
      basicPanel: 'Full financial panel',
      basicCurrency: 'Exchange rates PEN/USD',
      basicAI: 'AI recommendation models',
      basicComparator: 'Recommendation comparator (up to 3)',
      basicTransactions: 'Transactions, budgets and goals tracking',
      basicCategories: 'Basic categories (9)',
      basicChat: 'Chatbot (10 daily attempts)',
      basicProfile: 'User profile',
      premiumCurrency: 'Exchange rates +EUR, MXN',
      premiumComparator: 'Recommendation comparator (up to 10)',
      premiumStats: 'Comparative statistics + statistical tests',
      premiumCategories: '5 additional categories (total 14)',
      premiumChat: 'Unlimited chatbot + voice input',
      enterpriseCurrency: 'Exchange rates +30 global currencies',
      enterpriseCategories: '10 additional categories (total 24)',
    },
    basicSummary: 'Start organizing your finances with basic tools.',
    premiumSummary: 'Ideal for those seeking advanced statistics and more flexibility.',
    enterpriseSummary: 'For businesses or advanced users with global needs.',

    // ===== DOWNGRADE =====
    downgradeWarning: 'Warning! You are downgrading your plan',
    downgradeMessage: 'By downgrading, you will lose the following features:',
    downgradeFeature1: 'Access to advanced AI metrics',
    downgradeFeature2: 'You will need to re-enter your payment details',
    downgradeFeature3: 'Recommendations will be limited to the selected plan',
    confirmDowngrade: 'Yes, I am sure',
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const getInitialLanguage = () => {
    const savedLang = localStorage.getItem('financiaunt_language');
    if (savedLang) return savedLang;
    return 'es';
  };

  const [language, setLanguage] = useState(getInitialLanguage);

  useEffect(() => {
    localStorage.setItem('financiaunt_language', language);
  }, [language]);

  const t = (key) => {
    const keys = key.split('.');
    let value = translations[language];
    for (const k of keys) {
      value = value?.[k];
    }
    return value || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};