
import { createContext, useContext, useState, useEffect } from 'react'

const translations = {
  es: {
    login: 'Iniciar Sesión',
    register: 'Registrar',
    logout: 'Cerrar Sesión',
    dashboard: 'Panel',
    transactions: 'Transacciones',
    budgets: 'Presupuestos',
    goals: 'Metas',
    profile: 'Mi Perfil',
    settings: 'Configuración',
    plans: 'Planes',
    admin: 'Admin',
    users: 'Usuarios',
    statistics: 'Estadísticas',
    aiRecommendations: 'Recomendaciones IA',
    helpCenter: 'Centro de Ayuda',
    billing: 'Facturación',
    chat: 'Chat',
    theme: 'Tema',
    language: 'Idioma',
    light: 'Claro',
    dark: 'Oscuro',
    system: 'Sistema',
    save: 'Guardar',
    cancel: 'Cancelar',
    loading: 'Cargando...',
    error: 'Error',
    success: 'Éxito',
    credentialsIncorrect: 'Credenciales incorrectas',
    name: 'Nombre',
    email: 'Email',
    password: 'Contraseña',
    currentPassword: 'Contraseña Actual',
    newPassword: 'Nueva Contraseña',
    confirmPassword: 'Confirmar Contraseña',
    monthlyIncome: 'Ingreso Mensual',
    riskProfile: 'Perfil de Riesgo',
    advisorTone: 'Tono del Asesor',
    currency: 'Moneda',
    preferences: 'Preferencias',
    changePassword: 'Cambiar Contraseña',
    plan: 'Plan',
    role: 'Rol',
    basic: 'Básico',
    premium: 'Premium',
    enterprise: 'Enterprise',
    adminRole: 'Admin',
    welcome: 'Bienvenido',
    hello: 'Hola',
    goodbye: 'Adiós',
    features: {
      theme: 'Tema (Claro/Oscuro)',
      language: 'Idioma (ES/EN)',
      basicCurrency: 'Moneda base (PEN/USD)',
      basicAccounts: '3 Cuentas financieras',
      basicCategories: 'Categorías predefinidas',
      basicRecurring: '3 Transacciones recurrentes',
      basicManual: 'Manual PDF descargable',
      basicExport: 'Exportar mes actual (CSV)',
      basicAI: 'Top 3 recomendaciones IA',
      basicChat: '10 mensajes/día chatbot',
      premiumCurrency: 'Monedas: PEN/USD/EUR + 2 extra',
      premiumAccounts: 'Cuentas ilimitadas',
      premiumCategories: 'Categorías personalizadas',
      premiumRecurring: 'Transacciones recurrentes ilimitadas',
      premiumManual: 'PDF + Centro web de ayuda',
      premiumExport: 'Exportar histórico completo (CSV/Excel)',
      premiumAI: 'Top 10 recomendaciones IA',
      premiumChat: 'Chatbot ilimitado + ejecuta CRUD',
      enterpriseCurrency: '40+ monedas, TC cada 5 minutos',
      enterpriseAccounts: 'Cuentas ilimitadas por departamento',
      enterpriseCategories: 'Categorías globales + privadas',
      enterpriseRecurring: 'Transacciones recurrentes + flujo de aprobación',
      enterpriseManual: 'PDF white-label + Centro web avanzado',
      enterpriseExport: 'Exportar histórico + API',
      enterpriseAI: 'Top 10 recomendaciones + compara deptos',
      enterpriseChat: 'Chatbot ilimitado + genera reportes por voz'
    },
    selectPlan: 'Selecciona tu Plan',
    alreadyHave: 'Ya lo tienes',
    noAccount: '¿No tienes una cuenta?',
    signIn: 'Ingresa aquí',
    haveAccount: '¿Ya tienes cuenta?',
    createAccount: 'Crear Cuenta',
    startManaging: 'Comienza a gestionar tus finanzas',
    manageFinances: 'Gestiona tus finanzas de manera inteligente',
    choosePlan: 'Elegir Plan',
    creating: 'Creando...',
    passwordMismatch: 'Las contraseñas no coinciden',
    errorCreating: 'Error al crear la cuenta',
    yourEmail: 'tu@email.com',
    yourName: 'Tu nombre',
    // Dashboard translations
    loadingDashboard: 'Cargando panel...',
    retry: 'Reintentar',
    financialPanel: 'Panel financiero',
    dashboardDescription: 'Resumen operativo, recomendaciones inteligentes y alertas de ahorro.',
    generating: 'Generando...',
    generateReport: 'Generar Reporte PDF',
    aiPlan: 'Plan de IA',
    activeModels: 'Modelos activos',
    visibleRecommendations: 'Recomendaciones visibles',
    totalIncome: 'Ingresos Totales',
    totalExpenses: 'Gastos Totales',
    netSavings: 'Ahorro Neto',
    nextMonthPrediction: 'Predicción del próximo mes',
    projectedIncome: 'Ingreso proyectado',
    projectedExpenses: 'Gasto proyectado',
    projectedSavings: 'Ahorro proyectado',
    budgetAtRisk: 'Presupuesto en riesgo',
    expenseDistribution: 'Distribución de Gastos',
    budgetVsActual: 'Presupuesto vs Realidad',
    spendingTrends: 'Tendencias de Gastos',
    noExpenses: 'No hay gastos para mostrar',
    noBudgets: 'No hay presupuestos para mostrar',
    noTrendData: 'No hay datos suficientes para mostrar tendencias',
    aiRecommendationsTitle: 'Recomendaciones Inteligentes',
    visibleByPlan: 'visibles según tu plan',
    general: 'General',
    score: 'Puntuación',
    urgency: 'Urgencia',
    impact: 'Impacto',
    noRecommendations: 'No hay suficientes datos para generar recomendaciones.',
    recentTransactions: 'Transacciones Recientes',
    noTransactions: 'No hay transacciones registradas',
    // Chatbot translations
    financialAssistant: 'Asistente Financiero',
    typeMessage: 'Escribe tu mensaje...',
    botResponses: [
      'Claro, déjame revisar tu estado financiero.',
      '¡Excelente pregunta! Aquí tienes la información que necesitas.',
      'He analizado tus gastos y tengo algunas recomendaciones para ti.',
      '¿Te gustaría que genere un reporte ejecutivo con tus datos?'
    ],
    // Email verification translations
    emailVerificationRequired: 'Verificación de correo electrónico requerida',
    verifyYourEmail: 'Verifica tu correo electrónico',
    weSentCode: 'Hemos enviado un código de verificación a tu correo electrónico.',
    enterCode: 'Ingresa el código',
    verificationCode: 'Código de verificación',
    verify: 'Verificar',
    resendCode: 'Reenviar código',
    invalidCode: 'Código inválido',
    codeExpired: 'Código expirado',
    emailVerified: '¡Correo electrónico verificado exitosamente!',
    // Payment info translations
    mostPopular: 'Más Popular',
    perMonth: '/mes',
    // Card details
    cardholderName: 'Titular de la tarjeta',
    cardNumber: 'Número de tarjeta',
    expiry: 'Vencimiento',
    cvv: 'CVV',
    payment: 'Pago',
    enterPaymentDetails: 'Ingresa tus datos de pago a continuación.',
    // Admin stats translations
    loadingStats: 'Cargando estadísticas...',
    generalStats: 'Estadísticas Generales',
    totalUsers: 'Total Usuarios',
    totalTransactions: 'Total Transacciones',
    totalIncome: 'Ingresos Totales',
    totalExpenses: 'Gastos Totales',
    expensesByUser: 'Gastos por Usuario',
    incomeVsExpenses: 'Resumen Ingresos vs Gastos',
    noData: 'No hay datos para mostrar',
    noExpenseData: 'No hay datos de gastos',
    user: 'Usuario',
    // Transactions
    myTransactions: 'Mis Transacciones',
    newTransaction: 'Nueva Transacción',
    editTransaction: 'Editar Transacción',
    description: 'Descripción',
    amount: 'Monto',
    type: 'Tipo',
    income: 'Ingreso',
    expense: 'Gasto',
    date: 'Fecha',
    category: 'Categoría',
    account: 'Cuenta',
    recurring: 'Recurrente',
    actions: 'Acciones',
    edit: 'Editar',
    delete: 'Eliminar',
    save: 'Guardar',
    cancel: 'Cancelar',
    confirmDelete: '¿Estás seguro de que quieres eliminar esta transacción?',
    noTransactionsYet: 'No tienes transacciones aún',
    // Budgets
    myBudgets: 'Mis Presupuestos',
    newBudget: 'Nuevo Presupuesto',
    budgetLimit: 'Límite de Presupuesto',
    spent: 'Gastado',
    remaining: 'Restante',
    progress: 'Progreso',
    noBudgetsYet: 'No tienes presupuestos aún',
    // Goals
    myGoals: 'Mis Metas',
    newGoal: 'Nueva Meta',
    targetAmount: 'Monto Objetivo',
    saved: 'Ahorrado',
    deadline: 'Fecha Límite',
    noGoalsYet: 'No tienes metas aún',
    // Profile
    myProfile: 'Mi Perfil',
    personalInfo: 'Información Personal',
    securitySettings: 'Configuraciones de Seguridad',
    // Settings
    mySettings: 'Mis Configuraciones',
    // AI Recommendations
    aiRecommendationsTitle: 'Recomendaciones Inteligentes',
    // Help Center
    helpCenter: 'Centro de Ayuda',
    // Billing
    myBilling: 'Mi Facturación',
    // Admin Users
    adminUsers: 'Usuarios',
    allUsers: 'Todos los Usuarios',
    emailVerified: 'Correo Verificado',
    plan: 'Plan',
    role: 'Rol',
    createdAt: 'Creado',
    // Admin AI Stats
    aiStats: 'Estadísticas IA',
  },
  en: {
    login: 'Sign In',
    register: 'Register',
    logout: 'Sign Out',
    dashboard: 'Dashboard',
    transactions: 'Transactions',
    budgets: 'Budgets',
    goals: 'Goals',
    profile: 'My Profile',
    settings: 'Settings',
    plans: 'Plans',
    admin: 'Admin',
    users: 'Users',
    statistics: 'Statistics',
    aiRecommendations: 'AI Recommendations',
    helpCenter: 'Help Center',
    billing: 'Billing',
    chat: 'Chat',
    theme: 'Theme',
    language: 'Language',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    save: 'Save',
    cancel: 'Cancel',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    credentialsIncorrect: 'Incorrect credentials',
    name: 'Name',
    email: 'Email',
    password: 'Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    monthlyIncome: 'Monthly Income',
    riskProfile: 'Risk Profile',
    advisorTone: 'Advisor Tone',
    currency: 'Currency',
    preferences: 'Preferences',
    changePassword: 'Change Password',
    plan: 'Plan',
    role: 'Role',
    basic: 'Basic',
    premium: 'Premium',
    enterprise: 'Enterprise',
    adminRole: 'Admin',
    welcome: 'Welcome',
    hello: 'Hello',
    goodbye: 'Goodbye',
    features: {
      theme: 'Theme (Light/Dark)',
      language: 'Language (ES/EN)',
      basicCurrency: 'Base Currency (PEN/USD)',
      basicAccounts: '3 Financial Accounts',
      basicCategories: 'Predefined Categories',
      basicRecurring: '3 Recurring Transactions',
      basicManual: 'Downloadable PDF Manual',
      basicExport: 'Export Current Month (CSV)',
      basicAI: 'Top 3 AI Recommendations',
      basicChat: '10 messages/day chatbot',
      premiumCurrency: 'Currencies: PEN/USD/EUR + 2 extra',
      premiumAccounts: 'Unlimited Accounts',
      premiumCategories: 'Custom Categories',
      premiumRecurring: 'Unlimited Recurring Transactions',
      premiumManual: 'PDF + Web Help Center',
      premiumExport: 'Export Full History (CSV/Excel)',
      premiumAI: 'Top 10 AI Recommendations',
      premiumChat: 'Unlimited chatbot + CRUD execution',
      enterpriseCurrency: '40+ currencies, EC every 5 minutes',
      enterpriseAccounts: 'Unlimited Accounts per Department',
      enterpriseCategories: 'Global + Private Categories',
      enterpriseRecurring: 'Recurring Transactions + Approval Flow',
      enterpriseManual: 'White-label PDF + Advanced Help Center',
      enterpriseExport: 'Export History + API',
      enterpriseAI: 'Top 10 Recommendations + Compare Depts',
      enterpriseChat: 'Unlimited chatbot + voice reports'
    },
    selectPlan: 'Choose your Plan',
    alreadyHave: 'You already have it',
    noAccount: "Don't have an account?",
    signIn: 'Sign in here',
    haveAccount: 'Already have an account?',
    createAccount: 'Create Account',
    startManaging: 'Start managing your finances',
    manageFinances: 'Manage your finances smartly',
    choosePlan: 'Choose Plan',
    creating: 'Creating...',
    passwordMismatch: 'Passwords do not match',
    errorCreating: 'Error creating account',
    yourEmail: 'your@email.com',
    yourName: 'Your name',
    // Dashboard translations
    loadingDashboard: 'Loading dashboard...',
    retry: 'Retry',
    financialPanel: 'Financial Panel',
    dashboardDescription: 'Operational summary, smart recommendations and savings alerts.',
    generating: 'Generating...',
    generateReport: 'Generate PDF Report',
    aiPlan: 'AI Plan',
    activeModels: 'Active models',
    visibleRecommendations: 'Visible recommendations',
    totalIncome: 'Total Income',
    totalExpenses: 'Total Expenses',
    netSavings: 'Net Savings',
    nextMonthPrediction: 'Next month prediction',
    projectedIncome: 'Projected income',
    projectedExpenses: 'Projected expenses',
    projectedSavings: 'Projected savings',
    budgetAtRisk: 'Budget at risk',
    expenseDistribution: 'Expense Distribution',
    budgetVsActual: 'Budget vs Actual',
    spendingTrends: 'Spending Trends',
    noExpenses: 'No expenses to show',
    noBudgets: 'No budgets to show',
    noTrendData: 'Not enough data to show trends',
    aiRecommendationsTitle: 'Smart Recommendations',
    visibleByPlan: 'visible by your plan',
    general: 'General',
    score: 'Score',
    urgency: 'Urgency',
    impact: 'Impact',
    noRecommendations: 'Not enough data to generate recommendations.',
    recentTransactions: 'Recent Transactions',
    noTransactions: 'No transactions registered',
    // Chatbot translations
    financialAssistant: 'Financial Assistant',
    typeMessage: 'Type your message...',
    botResponses: [
      'Sure, let me check your financial status.',
      'Great question! Here is the information you need.',
      'I have analyzed your expenses and have some recommendations for you.',
      'Would you like me to generate an executive report with your data?'
    ],
    // Email verification translations
    emailVerificationRequired: 'Email verification required',
    verifyYourEmail: 'Verify your email',
    weSentCode: 'We have sent a verification code to your email.',
    enterCode: 'Enter the code',
    verificationCode: 'Verification code',
    verify: 'Verify',
    resendCode: 'Resend code',
    invalidCode: 'Invalid code',
    codeExpired: 'Code expired',
    emailVerified: 'Email verified successfully!',
    // Payment info translations
    mostPopular: 'Most Popular',
    perMonth: '/month',
    // Card details
    cardholderName: 'Cardholder name',
    cardNumber: 'Card number',
    expiry: 'Expiry',
    cvv: 'CVV',
    payment: 'Payment',
    enterPaymentDetails: 'Enter your payment details below.',
    // Admin stats translations
    loadingStats: 'Loading statistics...',
    generalStats: 'General Statistics',
    totalUsers: 'Total Users',
    totalTransactions: 'Total Transactions',
    totalIncome: 'Total Income',
    totalExpenses: 'Total Expenses',
    expensesByUser: 'Expenses by User',
    incomeVsExpenses: 'Income vs Expenses Summary',
    noData: 'No data to show',
    noExpenseData: 'No expense data',
    user: 'User',
    // Transactions
    myTransactions: 'My Transactions',
    newTransaction: 'New Transaction',
    editTransaction: 'Edit Transaction',
    description: 'Description',
    amount: 'Amount',
    type: 'Type',
    income: 'Income',
    expense: 'Expense',
    date: 'Date',
    category: 'Category',
    account: 'Account',
    recurring: 'Recurring',
    actions: 'Actions',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    confirmDelete: 'Are you sure you want to delete this transaction?',
    noTransactionsYet: 'You don\'t have any transactions yet',
    // Budgets
    myBudgets: 'My Budgets',
    newBudget: 'New Budget',
    budgetLimit: 'Budget Limit',
    spent: 'Spent',
    remaining: 'Remaining',
    progress: 'Progress',
    noBudgetsYet: 'You don\'t have any budgets yet',
    // Goals
    myGoals: 'My Goals',
    newGoal: 'New Goal',
    targetAmount: 'Target Amount',
    saved: 'Saved',
    deadline: 'Deadline',
    noGoalsYet: 'You don\'t have any goals yet',
    // Profile
    myProfile: 'My Profile',
    personalInfo: 'Personal Information',
    securitySettings: 'Security Settings',
    // Settings
    mySettings: 'My Settings',
    // AI Recommendations
    aiRecommendationsTitle: 'Smart Recommendations',
    // Help Center
    helpCenter: 'Help Center',
    // Billing
    myBilling: 'My Billing',
    // Admin Users
    adminUsers: 'Users',
    allUsers: 'All Users',
    emailVerified: 'Email Verified',
    plan: 'Plan',
    role: 'Role',
    createdAt: 'Created At',
    // Admin AI Stats
    aiStats: 'AI Statistics',
  }
}

const LanguageContext = createContext()

export const LanguageProvider = ({ children }) => {
  const getInitialLanguage = () => {
    const savedLang = localStorage.getItem('financiaunt_language')
    if (savedLang) return savedLang
    return 'es'
  }

  const [language, setLanguage] = useState(getInitialLanguage)

  useEffect(() => {
    localStorage.setItem('financiaunt_language', language)
  }, [language])

  const t = (key) => {
    const keys = key.split('.')
    let value = translations[language]
    for (const k of keys) {
      value = value?.[k]
    }
    return value || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
